[ERROR][2013-01-22 10:33:58]-[ 601ad84a000000a9:26922 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:110)]:保存JDA到BS的数据时出错!
[ 601ad84a000000a9:26922 ]org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [ insert into hht13101.htob1f (INSTNO,HHTACT,HHTDAT,HHTSTR,HHTSKU,HHTHAN,HHTSTO,HHTSPO,HHTARQ,HHTNSQ,HHTDSQ,HHTRAQ,HHTTRQ,HHTWTO,HHTWPO,HHTWAV,HHTLSD,HHTLRD,HHTLAD) values ('601ad84a000001a9' , 'C' , '20121115' , '13101' , '000703250' , '24' , '0' , '0' , '0' , '0' , '0' , '0' , '0' , '0' , '0' , '0' , '20111222' , '20121102')]; nested exception is java.sql.SQLException: Column count doesn't match value count at row 1
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.translate(SQLStateSQLExceptionTranslator.java:111)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.translate(SQLErrorCodeSQLExceptionTranslator.java:322)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:607)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:858)
	at com.hola.common.dao.StoreDao.execution(StoreDao.java:224)
	at com.hola.tarbs.service.TarBsService.addData(TarBsService.java:362)
	at com.hola.tarbs.service.TarBsService.access$4(TarBsService.java:353)
	at com.hola.tarbs.service.TarBsService$1.doInTransaction(TarBsService.java:304)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at com.hola.tarbs.service.TarBsService.executionForBs(TarBsService.java:282)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:107)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
Caused by: java.sql.SQLException: Column count doesn't match value count at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:798)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	... 15 more
[ERROR][2013-01-22 10:51:49]-[ 602b3418000000a9:3562 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:86)]:csv转换文件出错!!!,文件路径：D:\MW\csvFromMqToBs\13101\30122\HB1FT13101_20130122102640695_114802.CSV
[ 602b3418000000a9:3562 ]java.lang.NullPointerException
	at com.hola.tarbs.service.TarBsService.getLayerBean(TarBsService.java:447)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:81)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.main(TarBsService.java:176)
[ERROR][2013-01-22 10:54:12]-[ 602d6252000000a9:58797 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:86)]:csv转换文件出错!!!,文件路径：D:\MW\csvFromMqToBs\13101\30122\HB1FT13101_20130122102640695_114802.CSV
[ 602d6252000000a9:58797 ]java.lang.NullPointerException
	at com.hola.tarbs.service.TarBsService.getLayerBean(TarBsService.java:447)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:81)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.main(TarBsService.java:176)
[ERROR][2013-01-22 11:18:44]-[ 6043d10f000000a9:4906 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:110)]:保存JDA到BS的数据时出错!
[ 6043d10f000000a9:4906 ]org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [ insert into hht13101.htob1f (INSTNO,HHTACT,HHTDAT,HHTSTR,HHTSKU,HHTHAN,HHTSTO,HHTSPO,HHTARQ,HHTNSQ,HHTDSQ,HHTRAQ,HHTTRQ,HHTWTO,HHTWPO,HHTWAV,HHTLSD,HHTLRD,HHTLAD) values ('6043d10f000001a9' , 'C' , '20121115' , '13101' , '000106257' , '-1' , '0' , '0' , '0' , '0' , '0' , '0' , '0' , '0' , '0' , '0' , '20121110' , '')]; nested exception is java.sql.SQLException: Column count doesn't match value count at row 1
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.translate(SQLStateSQLExceptionTranslator.java:111)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.translate(SQLErrorCodeSQLExceptionTranslator.java:322)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:607)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:858)
	at com.hola.common.dao.StoreDao.execution(StoreDao.java:224)
	at com.hola.tarbs.service.TarBsService.addData(TarBsService.java:362)
	at com.hola.tarbs.service.TarBsService.access$4(TarBsService.java:353)
	at com.hola.tarbs.service.TarBsService$1.doInTransaction(TarBsService.java:304)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at com.hola.tarbs.service.TarBsService.executionForBs(TarBsService.java:282)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:107)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.main(TarBsService.java:176)
Caused by: java.sql.SQLException: Column count doesn't match value count at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:798)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	... 12 more
[ERROR][2013-01-22 13:50:15]-[ 60ce8d5b000000a9:67563 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:99)]:读取配置出错!!!
[ 60ce8d5b000000a9:67563 ]java.lang.NullPointerException
	at com.hola.tarbs.service.TarBsService.loadTarConfig(TarBsService.java:459)
	at com.hola.tarbs.service.TarBsService.getConfig(TarBsService.java:327)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:96)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
[ERROR][2013-01-22 13:50:16]-[ 60ce8d5b000001a9:68110 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:99)]:读取配置出错!!!
[ 60ce8d5b000001a9:68110 ]java.lang.NullPointerException
	at com.hola.tarbs.service.TarBsService.loadTarConfig(TarBsService.java:459)
	at com.hola.tarbs.service.TarBsService.getConfig(TarBsService.java:327)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:96)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
[ERROR][2013-01-22 13:50:16]-[ 60ce8d5b000002a9:68688 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:99)]:读取配置出错!!!
[ 60ce8d5b000002a9:68688 ]java.lang.NullPointerException
	at com.hola.tarbs.service.TarBsService.loadTarConfig(TarBsService.java:459)
	at com.hola.tarbs.service.TarBsService.getConfig(TarBsService.java:327)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:96)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
[ERROR][2013-01-22 13:50:17]-[ 60ce8d5b000003a9:69422 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:99)]:读取配置出错!!!
[ 60ce8d5b000003a9:69422 ]java.lang.NullPointerException
	at com.hola.tarbs.service.TarBsService.loadTarConfig(TarBsService.java:459)
	at com.hola.tarbs.service.TarBsService.getConfig(TarBsService.java:327)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:96)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
[ERROR][2013-01-22 13:50:18]-[ 60ce8d5b000004a9:69938 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:99)]:读取配置出错!!!
[ 60ce8d5b000004a9:69938 ]java.lang.NullPointerException
	at com.hola.tarbs.service.TarBsService.loadTarConfig(TarBsService.java:459)
	at com.hola.tarbs.service.TarBsService.getConfig(TarBsService.java:327)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:96)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
[ERROR][2013-01-22 13:50:18]-[ 60ce8d5b000005a9:70422 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:99)]:读取配置出错!!!
[ 60ce8d5b000005a9:70422 ]java.lang.NullPointerException
	at com.hola.tarbs.service.TarBsService.loadTarConfig(TarBsService.java:459)
	at com.hola.tarbs.service.TarBsService.getConfig(TarBsService.java:327)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:96)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
[ERROR][2013-01-22 13:50:19]-[ 60ce8d5b000006a9:71032 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:99)]:读取配置出错!!!
[ 60ce8d5b000006a9:71032 ]java.lang.NullPointerException
	at com.hola.tarbs.service.TarBsService.loadTarConfig(TarBsService.java:459)
	at com.hola.tarbs.service.TarBsService.getConfig(TarBsService.java:327)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:96)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
[ERROR][2013-01-22 13:50:19]-[ 60ce8d5b000007a9:71532 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:99)]:读取配置出错!!!
[ 60ce8d5b000007a9:71532 ]java.lang.NullPointerException
	at com.hola.tarbs.service.TarBsService.loadTarConfig(TarBsService.java:459)
	at com.hola.tarbs.service.TarBsService.getConfig(TarBsService.java:327)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:96)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
[ERROR][2013-01-22 13:50:20]-[ 60ce8d5b000008a9:72047 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:99)]:读取配置出错!!!
[ 60ce8d5b000008a9:72047 ]java.lang.NullPointerException
	at com.hola.tarbs.service.TarBsService.loadTarConfig(TarBsService.java:459)
	at com.hola.tarbs.service.TarBsService.getConfig(TarBsService.java:327)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:96)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
[ERROR][2013-01-22 13:50:20]-[ 60ce8d5b000009a9:72641 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:99)]:读取配置出错!!!
[ 60ce8d5b000009a9:72641 ]java.lang.NullPointerException
	at com.hola.tarbs.service.TarBsService.loadTarConfig(TarBsService.java:459)
	at com.hola.tarbs.service.TarBsService.getConfig(TarBsService.java:327)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:96)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
[ERROR][2013-01-22 13:50:21]-[ 60ce8d5b00000aa9:72938 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:99)]:读取配置出错!!!
[ 60ce8d5b00000aa9:72938 ]java.lang.NullPointerException
	at com.hola.tarbs.service.TarBsService.loadTarConfig(TarBsService.java:459)
	at com.hola.tarbs.service.TarBsService.getConfig(TarBsService.java:327)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:96)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
[ERROR][2013-01-22 13:57:50]-[ 60d57cde000000a9:73281 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:110)]:保存JDA到BS的数据时出错!
[ 60d57cde000000a9:73281 ]org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [ insert into hht13101.htoa1f (INSTNO,HHTSKU,HHTDSC,HHTCHN,HHTENN,HHTLTH,HHTWTH,HHTHGH,HHTDIM,HHTWGT,HHTSET,HHTEXP,HHTDEP,HHTDPN,HHTSDP,HHTSDN,HHTCLS,HHTCLN,HHTSCL,HHTSCN,HHTIPK,HHTCPK,HHTPKL,HHTPKW,HHTPKH,HHTPKG,HHTPIK,HHTMIN,HHTPAK,HHTMAT,HHTTAX,HHTVD#,HHTIPC,HHTCSF) values ('60d57cde000001a9' , '000705055' , '巴洛克实木西装架' , 'VALET' , 'VALET' , '7.5' , '48.0' , '30.5' , '0.0' , '3.0' , '0' , '0' , '004' , 'FURNITURE' , '043' , 'Home Organization' , '001' , 'Porch' , '001' , 'Clothes Tree' , '1.0' , '1.0' , '30.5' , '48.0' , '7.5' , '3.0' , 'Y' , '1.0' , '黄盒' , '' , '0.17' , '10206' , '27050552' , '')]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.translate(SQLExceptionSubclassTranslator.java:78)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.translate(SQLErrorCodeSQLExceptionTranslator.java:237)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:607)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:858)
	at com.hola.common.dao.StoreDao.execution(StoreDao.java:224)
	at com.hola.tarbs.service.TarBsService.addData(TarBsService.java:362)
	at com.hola.tarbs.service.TarBsService.access$4(TarBsService.java:353)
	at com.hola.tarbs.service.TarBsService$1.doInTransaction(TarBsService.java:304)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at com.hola.tarbs.service.TarBsService.executionForBs(TarBsService.java:282)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:107)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:798)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	... 15 more
[ERROR][2013-01-22 13:57:51]-[ 60d57cde000002a9:73860 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:110)]:保存JDA到BS的数据时出错!
[ 60d57cde000002a9:73860 ]org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [ insert into hht13101.htoa1f (INSTNO,HHTSKU,HHTDSC,HHTCHN,HHTENN,HHTLTH,HHTWTH,HHTHGH,HHTDIM,HHTWGT,HHTSET,HHTEXP,HHTDEP,HHTDPN,HHTSDP,HHTSDN,HHTCLS,HHTCLN,HHTSCL,HHTSCN,HHTIPK,HHTCPK,HHTPKL,HHTPKW,HHTPKH,HHTPKG,HHTPIK,HHTMIN,HHTPAK,HHTMAT,HHTTAX,HHTVD#,HHTIPC,HHTCSF) values ('60d57cde000003a9' , '000099493' , '超值三空柜－棕色' , '' , '' , '83.9' , '59.0' , '30.0' , '0.0' , '3.0' , '0' , '0' , '004' , 'FURNITURE' , '043' , 'Home Organization' , '005' , 'Study Room' , '001' , 'Bookcase' , '1.0' , '1.0' , '6.0' , '30.0' , '84.0' , '0.0' , '' , '1.0' , '' , '' , '0.17' , 'CUBIC 3' , '20994938' , '')]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.translate(SQLExceptionSubclassTranslator.java:78)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.translate(SQLErrorCodeSQLExceptionTranslator.java:237)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:607)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:858)
	at com.hola.common.dao.StoreDao.execution(StoreDao.java:224)
	at com.hola.tarbs.service.TarBsService.addData(TarBsService.java:362)
	at com.hola.tarbs.service.TarBsService.access$4(TarBsService.java:353)
	at com.hola.tarbs.service.TarBsService$1.doInTransaction(TarBsService.java:304)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at com.hola.tarbs.service.TarBsService.executionForBs(TarBsService.java:282)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:107)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:798)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	... 15 more
[ERROR][2013-01-22 13:57:51]-[ 60d57cde000004a9:74344 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:110)]:保存JDA到BS的数据时出错!
[ 60d57cde000004a9:74344 ]org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [ insert into hht13101.htoa1f (INSTNO,HHTSKU,HHTDSC,HHTCHN,HHTENN,HHTLTH,HHTWTH,HHTHGH,HHTDIM,HHTWGT,HHTSET,HHTEXP,HHTDEP,HHTDPN,HHTSDP,HHTSDN,HHTCLS,HHTCLN,HHTSCL,HHTSCN,HHTIPK,HHTCPK,HHTPKL,HHTPKW,HHTPKH,HHTPKG,HHTPIK,HHTMIN,HHTPAK,HHTMAT,HHTTAX,HHTVD#,HHTIPC,HHTCSF) values ('60d57cde000005a9' , '000089209' , 'Do Clear儿童牙刷(6-12岁' , '' , '' , '12.0' , '1.0' , '2.0' , '0.0' , '0.0080' , '0' , '0' , '001' , 'TEXTILE' , '015' , 'BATH & BODY CARE' , '010' , '个人清洁保养用品' , '001' , 'ORAL CARE' , '1.0' , '6.0' , '12.0' , '6.0' , '72.0' , '0.48' , '' , '1.0' , '盒装' , '' , '0.17' , '68B' , '20892098' , '')]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.translate(SQLExceptionSubclassTranslator.java:78)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.translate(SQLErrorCodeSQLExceptionTranslator.java:237)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:607)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:858)
	at com.hola.common.dao.StoreDao.execution(StoreDao.java:224)
	at com.hola.tarbs.service.TarBsService.addData(TarBsService.java:362)
	at com.hola.tarbs.service.TarBsService.access$4(TarBsService.java:353)
	at com.hola.tarbs.service.TarBsService$1.doInTransaction(TarBsService.java:304)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at com.hola.tarbs.service.TarBsService.executionForBs(TarBsService.java:282)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:107)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:798)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	... 15 more
[ERROR][2013-01-22 13:57:52]-[ 60d57cde000006a9:74875 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:110)]:保存JDA到BS的数据时出错!
[ 60d57cde000006a9:74875 ]org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [ insert into hht13101.htoa1f (INSTNO,HHTSKU,HHTDSC,HHTCHN,HHTENN,HHTLTH,HHTWTH,HHTHGH,HHTDIM,HHTWGT,HHTSET,HHTEXP,HHTDEP,HHTDPN,HHTSDP,HHTSDN,HHTCLS,HHTCLN,HHTSCL,HHTSCN,HHTIPK,HHTCPK,HHTPKL,HHTPKW,HHTPKH,HHTPKG,HHTPIK,HHTMIN,HHTPAK,HHTMAT,HHTTAX,HHTVD#,HHTIPC,HHTCSF) values ('60d57cde000007a9' , '000078913' , '天际智能陶瓷电饭煲CFXB-40K' , '' , '' , '30.0' , '20.0' , '30.0' , '0.0' , '1.0' , '0' , '0' , '003' , 'LIGHTING & APPLIANCE' , '032' , 'APPLIANCE' , '001' , 'COOKING APPLIANCE' , '006' , 'ELEC.STEWPOT' , '1.0' , '1.0' , '30.0' , '20.0' , '30.0' , '1.0' , '' , '1.0' , '' , '' , '0.17' , '' , '20789138' , '')]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.translate(SQLExceptionSubclassTranslator.java:78)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.translate(SQLErrorCodeSQLExceptionTranslator.java:237)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:607)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:858)
	at com.hola.common.dao.StoreDao.execution(StoreDao.java:224)
	at com.hola.tarbs.service.TarBsService.addData(TarBsService.java:362)
	at com.hola.tarbs.service.TarBsService.access$4(TarBsService.java:353)
	at com.hola.tarbs.service.TarBsService$1.doInTransaction(TarBsService.java:304)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at com.hola.tarbs.service.TarBsService.executionForBs(TarBsService.java:282)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:107)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:798)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	... 15 more
[ERROR][2013-01-22 13:57:52]-[ 60d57cde000008a9:75297 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:110)]:保存JDA到BS的数据时出错!
[ 60d57cde000008a9:75297 ]org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [ insert into hht13101.htoa1f (INSTNO,HHTSKU,HHTDSC,HHTCHN,HHTENN,HHTLTH,HHTWTH,HHTHGH,HHTDIM,HHTWGT,HHTSET,HHTEXP,HHTDEP,HHTDPN,HHTSDP,HHTSDN,HHTCLS,HHTCLN,HHTSCL,HHTSCN,HHTIPK,HHTCPK,HHTPKL,HHTPKW,HHTPKH,HHTPKG,HHTPIK,HHTMIN,HHTPAK,HHTMAT,HHTTAX,HHTVD#,HHTIPC,HHTCSF) values ('60d57cde000009a9' , '000068642' , '艾美特风扇赠雨伞１个' , '' , '' , '1.0' , '1.0' , '1.0' , '0.0' , '1.0' , '0' , '0' , '003' , 'LIGHTING & APPLIANCE' , '032' , 'APPLIANCE' , '008' , 'SEASONAL APPLIANCE' , '001' , 'FANS' , '1.0' , '1.0' , '0.0' , '0.0' , '0.0' , '0.0' , '' , '1.0' , '' , '' , '0.17' , '' , '20686420' , '')]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.translate(SQLExceptionSubclassTranslator.java:78)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.translate(SQLErrorCodeSQLExceptionTranslator.java:237)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:607)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:858)
	at com.hola.common.dao.StoreDao.execution(StoreDao.java:224)
	at com.hola.tarbs.service.TarBsService.addData(TarBsService.java:362)
	at com.hola.tarbs.service.TarBsService.access$4(TarBsService.java:353)
	at com.hola.tarbs.service.TarBsService$1.doInTransaction(TarBsService.java:304)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at com.hola.tarbs.service.TarBsService.executionForBs(TarBsService.java:282)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:107)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:798)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	... 15 more
[ERROR][2013-01-22 13:57:53]-[ 60d57cde00000aa9:75688 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:110)]:保存JDA到BS的数据时出错!
[ 60d57cde00000aa9:75688 ]org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [ insert into hht13101.htoa1f (INSTNO,HHTSKU,HHTDSC,HHTCHN,HHTENN,HHTLTH,HHTWTH,HHTHGH,HHTDIM,HHTWGT,HHTSET,HHTEXP,HHTDEP,HHTDPN,HHTSDP,HHTSDN,HHTCLS,HHTCLN,HHTSCL,HHTSCN,HHTIPK,HHTCPK,HHTPKL,HHTPKW,HHTPKH,HHTPKG,HHTPIK,HHTMIN,HHTPAK,HHTMAT,HHTTAX,HHTVD#,HHTIPC,HHTCSF) values ('60d57cde00000ba9' , '000058493' , '博朗电动牙刷D12523' , '' , '' , '1.0' , '1.0' , '1.0' , '0.0' , '1.0' , '0' , '0' , '003' , 'LIGHTING & APPLIANCE' , '032' , 'APPLIANCE' , '009' , 'PERSONAL CARE' , '002' , '个人护理类－博朗' , '1.0' , '1.0' , '0.0' , '0.0' , '0.0' , '0.0' , '' , '1.0' , '' , '' , '0.17' , 'D12523' , '20584931' , '')]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.translate(SQLExceptionSubclassTranslator.java:78)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.translate(SQLErrorCodeSQLExceptionTranslator.java:237)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:607)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:858)
	at com.hola.common.dao.StoreDao.execution(StoreDao.java:224)
	at com.hola.tarbs.service.TarBsService.addData(TarBsService.java:362)
	at com.hola.tarbs.service.TarBsService.access$4(TarBsService.java:353)
	at com.hola.tarbs.service.TarBsService$1.doInTransaction(TarBsService.java:304)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at com.hola.tarbs.service.TarBsService.executionForBs(TarBsService.java:282)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:107)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:798)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	... 15 more
[ERROR][2013-01-22 13:57:53]-[ 60d57cde00000ca9:76141 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:110)]:保存JDA到BS的数据时出错!
[ 60d57cde00000ca9:76141 ]org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [ insert into hht13101.htoa1f (INSTNO,HHTSKU,HHTDSC,HHTCHN,HHTENN,HHTLTH,HHTWTH,HHTHGH,HHTDIM,HHTWGT,HHTSET,HHTEXP,HHTDEP,HHTDPN,HHTSDP,HHTSDN,HHTCLS,HHTCLN,HHTSCL,HHTSCN,HHTIPK,HHTCPK,HHTPKL,HHTPKW,HHTPKH,HHTPKG,HHTPIK,HHTMIN,HHTPAK,HHTMAT,HHTTAX,HHTVD#,HHTIPC,HHTCSF) values ('60d57cde00000da9' , '000048341' , '餐椅' , '' , '' , '1.0' , '1.0' , '1.0' , '0.0' , '1.0' , '0' , '0' , '008' , '大家具' , '086' , 'FURNITURE' , '003' , 'recliner' , '002' , 'leather recliner' , '1.0' , '1.0' , '1.0' , '1.0' , '1.0' , '1.0' , '' , '1.0' , '' , '' , '0.17' , 'Y2002' , '20483418' , '')]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.translate(SQLExceptionSubclassTranslator.java:78)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.translate(SQLErrorCodeSQLExceptionTranslator.java:237)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:607)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:858)
	at com.hola.common.dao.StoreDao.execution(StoreDao.java:224)
	at com.hola.tarbs.service.TarBsService.addData(TarBsService.java:362)
	at com.hola.tarbs.service.TarBsService.access$4(TarBsService.java:353)
	at com.hola.tarbs.service.TarBsService$1.doInTransaction(TarBsService.java:304)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at com.hola.tarbs.service.TarBsService.executionForBs(TarBsService.java:282)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:107)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:798)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	... 15 more
[ERROR][2013-01-22 13:57:54]-[ 60d57cde00000ea9:76594 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:110)]:保存JDA到BS的数据时出错!
[ 60d57cde00000ea9:76594 ]org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [ insert into hht13101.htoa1f (INSTNO,HHTSKU,HHTDSC,HHTCHN,HHTENN,HHTLTH,HHTWTH,HHTHGH,HHTDIM,HHTWGT,HHTSET,HHTEXP,HHTDEP,HHTDPN,HHTSDP,HHTSDN,HHTCLS,HHTCLN,HHTSCL,HHTSCN,HHTIPK,HHTCPK,HHTPKL,HHTPKW,HHTPKH,HHTPKG,HHTPIK,HHTMIN,HHTPAK,HHTMAT,HHTTAX,HHTVD#,HHTIPC,HHTCSF) values ('60d57cde00000fa9' , '000038247' , '好太太折叠衣架GW598' , '' , '' , '20.0' , '18.0' , '135.0' , '0.0' , '5.0' , '0' , '0' , '002' , 'HOUSEWARE' , '022' , 'HOUSEHOLD ARTICLES' , '007' , 'LAUNDRY' , '003' , 'SUN-DRIED RACKS' , '1.0' , '1.0' , '0.0' , '0.0' , '0.0' , '0.0' , '' , '1.0' , '' , '' , '0.17' , 'GW598' , '20382476' , '')]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.translate(SQLExceptionSubclassTranslator.java:78)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.translate(SQLErrorCodeSQLExceptionTranslator.java:237)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:607)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:858)
	at com.hola.common.dao.StoreDao.execution(StoreDao.java:224)
	at com.hola.tarbs.service.TarBsService.addData(TarBsService.java:362)
	at com.hola.tarbs.service.TarBsService.access$4(TarBsService.java:353)
	at com.hola.tarbs.service.TarBsService$1.doInTransaction(TarBsService.java:304)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at com.hola.tarbs.service.TarBsService.executionForBs(TarBsService.java:282)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:107)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:798)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	... 15 more
[ERROR][2013-01-22 13:57:54]-[ 60d57cde000010a9:77110 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:110)]:保存JDA到BS的数据时出错!
[ 60d57cde000010a9:77110 ]org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [ insert into hht13101.htoa1f (INSTNO,HHTSKU,HHTDSC,HHTCHN,HHTENN,HHTLTH,HHTWTH,HHTHGH,HHTDIM,HHTWGT,HHTSET,HHTEXP,HHTDEP,HHTDPN,HHTSDP,HHTSDN,HHTCLS,HHTCLN,HHTSCL,HHTSCN,HHTIPK,HHTCPK,HHTPKL,HHTPKW,HHTPKH,HHTPKG,HHTPIK,HHTMIN,HHTPAK,HHTMAT,HHTTAX,HHTVD#,HHTIPC,HHTCSF) values ('60d57cde000011a9' , '000028131' , 'EOS卷帘隔光卡通系列' , '' , '' , '1.0' , '1.0' , '1.0' , '0.0' , '1.0' , '0' , '0' , '001' , 'TEXTILE' , '016' , 'living textile' , '005' , 'Others' , '001' , 'Others' , '1.0' , '1.0' , '1.0' , '1.0' , '1.0' , '1.0' , '' , '1.0' , '' , '' , '0.17' , '83/北京' , '20281311' , '')]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.translate(SQLExceptionSubclassTranslator.java:78)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.translate(SQLErrorCodeSQLExceptionTranslator.java:237)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:607)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:858)
	at com.hola.common.dao.StoreDao.execution(StoreDao.java:224)
	at com.hola.tarbs.service.TarBsService.addData(TarBsService.java:362)
	at com.hola.tarbs.service.TarBsService.access$4(TarBsService.java:353)
	at com.hola.tarbs.service.TarBsService$1.doInTransaction(TarBsService.java:304)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at com.hola.tarbs.service.TarBsService.executionForBs(TarBsService.java:282)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:107)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:798)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	... 15 more
[ERROR][2013-01-22 13:57:55]-[ 60d57cde000012a9:77938 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:110)]:保存JDA到BS的数据时出错!
[ 60d57cde000012a9:77938 ]org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [ insert into hht13101.htoa1f (INSTNO,HHTSKU,HHTDSC,HHTCHN,HHTENN,HHTLTH,HHTWTH,HHTHGH,HHTDIM,HHTWGT,HHTSET,HHTEXP,HHTDEP,HHTDPN,HHTSDP,HHTSDN,HHTCLS,HHTCLN,HHTSCL,HHTSCN,HHTIPK,HHTCPK,HHTPKL,HHTPKW,HHTPKH,HHTPKG,HHTPIK,HHTMIN,HHTPAK,HHTMAT,HHTTAX,HHTVD#,HHTIPC,HHTCSF) values ('60d57cde000013a9' , '000018081' , '健士霸9盎司多彩降解口杯' , '' , '' , '1.0' , '1.0' , '1.0' , '0.0' , '1.0' , '0' , '0' , '002' , 'HOUSEWARE' , '021' , 'KITCHEN WARE' , '008' , '食物存儲用品' , '006' , '一次性用品' , '1.0' , '20.0' , '1.0' , '1.0' , '1.0' , '1.0' , '' , '1.0' , '' , '' , '0.17' , 'A-521' , '20180812' , '')]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.translate(SQLExceptionSubclassTranslator.java:78)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.translate(SQLErrorCodeSQLExceptionTranslator.java:237)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:607)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:858)
	at com.hola.common.dao.StoreDao.execution(StoreDao.java:224)
	at com.hola.tarbs.service.TarBsService.addData(TarBsService.java:362)
	at com.hola.tarbs.service.TarBsService.access$4(TarBsService.java:353)
	at com.hola.tarbs.service.TarBsService$1.doInTransaction(TarBsService.java:304)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at com.hola.tarbs.service.TarBsService.executionForBs(TarBsService.java:282)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:107)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:798)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	... 15 more
[ERROR][2013-01-22 13:57:56]-[ 60d57cde000014a9:78360 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:110)]:保存JDA到BS的数据时出错!
[ 60d57cde000014a9:78360 ]org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [ insert into hht13101.htoa1f (INSTNO,HHTSKU,HHTDSC,HHTCHN,HHTENN,HHTLTH,HHTWTH,HHTHGH,HHTDIM,HHTWGT,HHTSET,HHTEXP,HHTDEP,HHTDPN,HHTSDP,HHTSDN,HHTCLS,HHTCLN,HHTSCL,HHTSCN,HHTIPK,HHTCPK,HHTPKL,HHTPKW,HHTPKH,HHTPKG,HHTPIK,HHTMIN,HHTPAK,HHTMAT,HHTTAX,HHTVD#,HHTIPC,HHTCSF) values ('60d57cde000015a9' , '000007518' , '长方形地垫(灵感/橄榄绿)' , '' , '' , '97.0' , '52.0' , '0.5' , '0.0' , '1.0' , '0' , '0' , '002' , 'HOUSEWARE' , '022' , 'HOUSEHOLD ARTICLES' , '009' , '卫浴配件(TBC)' , '002' , '浴室防滑垫' , '1.0' , '1.0' , '50.0' , '80.0' , '1.0' , '1.0' , '' , '1.0' , '' , '' , '0.17' , 'BDC0' , '20075187' , '')]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.translate(SQLExceptionSubclassTranslator.java:78)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.translate(SQLErrorCodeSQLExceptionTranslator.java:237)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:607)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:858)
	at com.hola.common.dao.StoreDao.execution(StoreDao.java:224)
	at com.hola.tarbs.service.TarBsService.addData(TarBsService.java:362)
	at com.hola.tarbs.service.TarBsService.access$4(TarBsService.java:353)
	at com.hola.tarbs.service.TarBsService$1.doInTransaction(TarBsService.java:304)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at com.hola.tarbs.service.TarBsService.executionForBs(TarBsService.java:282)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:107)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:798)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	... 15 more
[ERROR][2013-01-22 14:22:06]-[ 60eb7457000000a9:18610 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:110)]:保存JDA到BS的数据时出错!
[ 60eb7457000000a9:18610 ]org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [ insert into hht13101.htoa1f (INSTNO,HHTSKU,HHTDSC,HHTCHN,HHTENN,HHTLTH,HHTWTH,HHTHGH,HHTDIM,HHTWGT,HHTSET,HHTEXP,HHTDEP,HHTDPN,HHTSDP,HHTSDN,HHTCLS,HHTCLN,HHTSCL,HHTSCN,HHTIPK,HHTCPK,HHTPKL,HHTPKW,HHTPKH,HHTPKG,HHTPIK,HHTMIN,HHTPAK,HHTMAT,HHTTAX,HHTVD,HHTIPC,HHTCSF) values ('60eb7457000001a9' , '000105865' , 'NBA男士旅行护理包（活炭深层' , '' , '' , '11.7' , '8.3' , '12.0' , '0.0' , '0.195' , '0' , '0' , '001' , 'TEXTILE' , '015' , 'BATH & BODY CARE' , '010' , '个人清洁保养用品' , '007' , 'MAN'S CARE' , '3.0' , '24.0' , '20.0' , '48.5' , '39.0' , '4.86' , '' , '3.0' , '' , '' , '0.17' , '' , '21058653' , '')]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'S CARE' , '3.0' , '24.0' , '20.0' , '48.5' , '39.0' , '4.86' , '' , '3.0' , '' ,' at line 1
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.translate(SQLExceptionSubclassTranslator.java:78)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.translate(SQLErrorCodeSQLExceptionTranslator.java:237)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:607)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:858)
	at com.hola.common.dao.StoreDao.execution(StoreDao.java:224)
	at com.hola.tarbs.service.TarBsService.addData(TarBsService.java:362)
	at com.hola.tarbs.service.TarBsService.access$4(TarBsService.java:353)
	at com.hola.tarbs.service.TarBsService$1.doInTransaction(TarBsService.java:304)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at com.hola.tarbs.service.TarBsService.executionForBs(TarBsService.java:282)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:107)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.main(TarBsService.java:176)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'S CARE' , '3.0' , '24.0' , '20.0' , '48.5' , '39.0' , '4.86' , '' , '3.0' , '' ,' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:798)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	... 12 more
[ERROR][2013-01-22 14:27:02]-[ 60ee7737000000a9:117813 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:110)]:保存JDA到BS的数据时出错!
[ 60ee7737000000a9:117813 ]org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [ insert into hht13101.htoa1f (INSTNO,HHTSKU,HHTDSC,HHTCHN,HHTENN,HHTLTH,HHTWTH,HHTHGH,HHTDIM,HHTWGT,HHTSET,HHTEXP,HHTDEP,HHTDPN,HHTSDP,HHTSDN,HHTCLS,HHTCLN,HHTSCL,HHTSCN,HHTIPK,HHTCPK,HHTPKL,HHTPKW,HHTPKH,HHTPKG,HHTPIK,HHTMIN,HHTPAK,HHTMAT,HHTTAX,HHTVD,HHTIPC,HHTCSF) values ('60ee7737000001a9' , '000105865' , 'NBA男士旅行护理包（活炭深层' , '' , '' , '11.7' , '8.3' , '12.0' , '0.0' , '0.195' , '0' , '0' , '001' , 'TEXTILE' , '015' , 'BATH & BODY CARE' , '010' , '个人清洁保养用品' , '007' insert into hht13101.htoa1f (INSTNO,HHTSKU,HHTDSC,HHTCHN,HHTENN,HHTLTH,HHTWTH,HHTHGH,HHTDIM,HHTWGT,HHTSET,HHTEXP,HHTDEP,HHTDPN,HHTSDP,HHTSDN,HHTCLS,HHTCLN,HHTSCL,HHTSCN,HHTIPK,HHTCPK,HHTPKL,HHTPKW,HHTPKH,HHTPKG,HHTPIK,HHTMIN,HHTPAK,HHTMAT,HHTTAX,HHTVD,HHTIPC,HHTCSF) values ('60ee7737000001a9' , '000105865' , 'NBA男士旅行护理包（活炭深层' , '' , '' , '11.7' , '8.3' , '12.0' , '0.0' , '0.195' , '0' , '0' , '001' , 'TEXTILE' , '015' , 'BATH & BODY CARE' , '010' , '个人清洁保养用品' , '007' , 'MAN\'S CARE' , '3.0' , '24.0' , '20.0' , '48.5' , '39.0' , '4.86' , '' , '3.0' , '' , '' , '0.17' , '' , '21058653' , '')]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'insert into hht13101.htoa1f (INSTNO,HHTSKU,HHTDSC,HHTCHN,HHTENN,HHTLTH,HHTWTH,HH' at line 1
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.translate(SQLExceptionSubclassTranslator.java:78)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.translate(SQLErrorCodeSQLExceptionTranslator.java:237)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:607)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:858)
	at com.hola.common.dao.StoreDao.execution(StoreDao.java:224)
	at com.hola.tarbs.service.TarBsService.addData(TarBsService.java:362)
	at com.hola.tarbs.service.TarBsService.access$4(TarBsService.java:353)
	at com.hola.tarbs.service.TarBsService$1.doInTransaction(TarBsService.java:304)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at com.hola.tarbs.service.TarBsService.executionForBs(TarBsService.java:282)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:107)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.main(TarBsService.java:176)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'insert into hht13101.htoa1f (INSTNO,HHTSKU,HHTDSC,HHTCHN,HHTENN,HHTLTH,HHTWTH,HH' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:798)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	... 12 more
[ERROR][2013-01-22 15:39:04]-[ 61322999000000a9:54266 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:99)]:读取配置出错!!!
[ 61322999000000a9:54266 ]java.lang.NullPointerException
	at com.hola.tarbs.service.TarBsService.loadTarConfig(TarBsService.java:459)
	at com.hola.tarbs.service.TarBsService.getConfig(TarBsService.java:327)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:96)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
[ERROR][2013-01-22 15:41:59]-[ 6134d698000000a9:2625 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:110)]:保存JDA到BS的数据时出错!
[ 6134d698000000a9:2625 ]org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [ insert into hht13101.htoa1f (INSTNO,HHTSKU,HHTDSC,HHTCHN,HHTENN,HHTLTH,HHTWTH,HHTHGH,HHTDIM,HHTWGT,HHTSET,HHTEXP,HHTDEP,HHTDPN,HHTSDP,HHTSDN,HHTCLS,HHTCLN,HHTSCL,HHTSCN,HHTIPK,HHTCPK,HHTPKL,HHTPKW,HHTPKH,HHTPKG,HHTPIK,HHTMIN,HHTPAK,HHTMAT,HHTTAX,HHTVD#,HHTIPC,HHTCSF) values ('60f0d79d000001a9' , '000068642' , '艾美特风扇赠雨伞１个' , '' , '' , '1.0' , '1.0' , '1.0' , '0.0' , '1.0' , '0' , '0' , '003' , 'LIGHTING & APPLIANCE' , '032' , 'APPLIANCE' , '008' , 'SEASONAL APPLIANCE' , '001' , 'FANS' , '1.0' , '1.0' , '0.0' , '0.0' , '0.0' , '0.0' , '' , '1.0' , '' , '' , '0.17' , '' , '20686420' , '')]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.translate(SQLExceptionSubclassTranslator.java:78)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.translate(SQLErrorCodeSQLExceptionTranslator.java:237)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:607)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:858)
	at com.hola.common.dao.StoreDao.execution(StoreDao.java:224)
	at com.hola.tarbs.service.TarBsService.addData(TarBsService.java:362)
	at com.hola.tarbs.service.TarBsService.access$4(TarBsService.java:353)
	at com.hola.tarbs.service.TarBsService$1.doInTransaction(TarBsService.java:304)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at com.hola.tarbs.service.TarBsService.executionForBs(TarBsService.java:282)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:107)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.main(TarBsService.java:176)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:798)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	... 12 more
[ERROR][2013-01-22 17:23:21]-[ 6191a766000000a9:17407 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:110)]:保存JDA到BS的数据时出错!
[ 6191a766000000a9:17407 ]org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [ insert into hht13101.jdac1h (INSTNO,HHTACT,HHTTYP,HHTNO,HHTSTS,HHTFLC,HHTTLC,HHTOCD,HHTRCW,HHTPCD,HHTPNM,HHTVEN,HHTEDT,HHTBDT,HHTMA1,HHTMA2,HHTESY,HHTHNO,HHTEUS,HHTSKU,HHTUNT,HHTRQT,HHTAQT,HHTSRN,HHTNOT) values ('6191a766000001a9' , 'C' , 'TRF' , '201568' , 'A' , '13110' , '13101' , 'R1' , '' , '1' , '手工单- REGULAR ORDER' , '' , '20121115' , '20121115' , '' , '' , 'HHT' , '' , '' , '000016377' , '1' , '1' , '1' , '' , '')]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'HHTVEN' in 'field list'
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.translate(SQLExceptionSubclassTranslator.java:78)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.translate(SQLErrorCodeSQLExceptionTranslator.java:237)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:607)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:858)
	at com.hola.common.dao.StoreDao.execution(StoreDao.java:224)
	at com.hola.tarbs.service.TarBsService.addData(TarBsService.java:362)
	at com.hola.tarbs.service.TarBsService.access$4(TarBsService.java:353)
	at com.hola.tarbs.service.TarBsService$1.doInTransaction(TarBsService.java:304)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at com.hola.tarbs.service.TarBsService.executionForBs(TarBsService.java:282)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:107)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'HHTVEN' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:798)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	... 15 more
[ERROR][2013-01-22 17:46:45]-[ 61a71712000000a9:16750 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:99)]:读取配置出错!!!
[ 61a71712000000a9:16750 ]java.lang.NullPointerException
	at com.hola.tarbs.service.TarBsService.loadTarConfig(TarBsService.java:459)
	at com.hola.tarbs.service.TarBsService.getConfig(TarBsService.java:327)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:96)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.executionOneFile(TarBsService.java:160)
	at com.hola.tarbs.service.TarBsService.getCsvfilesForMqSaveBs(TarBsService.java:139)
	at com.hola.tarbs.LoadCsvExecutionBs.receiveMqExecutionBsForAllStore(LoadCsvExecutionBs.java:26)
	at Test.main(Test.java:22)
[ERROR][2013-01-22 17:47:32]-[ 61a7cd33000000a9:1672 ][com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:110)]:保存JDA到BS的数据时出错!
[ 61a7cd33000000a9:1672 ]org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [ insert into hht13101.htoa5f (INSTNO,A5STR,A5STRN,A5HDO,A5HDOD,A5GRP,A5GRPD,A5SLOC,A5FLG,A5FLGD,A5ADD,A5TEL,A5FAX,A5SDAT,A5WHS,A5FIL1,A5FIL2,A5FIL3,A5FIL4,A5FIL5) values ('61a7cd33000001a9' , '53101' , 'Mango门店' , 'S' , '' , '00311' , '' , '53101' , '6' , '6- Mango Store' , 'Mango门店' , '' , '' , '20100101' , '13196' , '' , '' , '' , '' , '')]; SQL state [HY000]; error code [1366]; Incorrect decimal value: '' for column 'A5FIL5' at row 1; nested exception is java.sql.SQLException: Incorrect decimal value: '' for column 'A5FIL5' at row 1
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.translate(SQLStateSQLExceptionTranslator.java:124)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.translate(SQLErrorCodeSQLExceptionTranslator.java:322)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:607)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:858)
	at com.hola.common.dao.StoreDao.execution(StoreDao.java:224)
	at com.hola.tarbs.service.TarBsService.addData(TarBsService.java:362)
	at com.hola.tarbs.service.TarBsService.access$4(TarBsService.java:353)
	at com.hola.tarbs.service.TarBsService$1.doInTransaction(TarBsService.java:304)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:127)
	at com.hola.tarbs.service.TarBsService.executionForBs(TarBsService.java:282)
	at com.hola.tarbs.service.TarBsService.saveCsvToBs(TarBsService.java:107)
	at com.hola.tarbs.service.TarBsService.csvFileForMqSaveBs(TarBsService.java:192)
	at com.hola.tarbs.service.TarBsService.main(TarBsService.java:176)
Caused by: java.sql.SQLException: Incorrect decimal value: '' for column 'A5FIL5' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:798)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	... 12 more
